version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest

  backend-server:
    build:
      context: ./uniplac-dev-web-nestjs
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    links:
      - "db"
    depends_on:
      - "db"

  frontend-server:
    build:
      context: ./uniplac-dev-web-frontend-nextjs
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - "backend-server"
    depends_on:
      - "db"
